### PR TITLE
Fixes #2 (Pack lir for library use with 0.8.3)

### LINKED ISSUE #2: [0.8.3] Fully qualify modules and expose the types module
@filib In order to use `Lir` as a library, there are two things which we should do, at minimum:

* Fully qualify the modules: I propose something like "Lir.XXX", to start with. So having something like "Lir.Types, Lir.Validation, etc."

* Expose the `Types` module.

👍 ?

### PR DESCRIPTION
**Pull request by adinapoli**
@filib I have re-run the tests and checked this is still building fine. Hopefully this should do the trick.

### CODE REVIEW

**Comment by adinapoli** [comment]
This is still no being picked up from a 3rd-party project, let me keep this on a hold and re-open when I figure out what's going on.

**Comment by adinapoli** [comment]
@filib To make things work I had to rename the library as "purescript-lir" inside `bower.json`. Go figure!

**Comment by filib** [comment]
@adinapoli before I merge this, [did you see my comment?](https://github.com/filib/lir/issues/2#issuecomment-265112262)

**Comment by adinapoli** [comment]
@filib Missed it, my bad! Fix incoming!

**Comment by adinapoli** [comment]
@filib Hope you don't mind, but in retrospective I think those are all very useful function to have at our disposal, so I ended up exposing everything. Do you have any strong sentiment for not doing so?

**Comment by filib** [comment]
No strong sentiment. It was similar to previous remark about the nature of the library being intended mostly for JS consumption, where I wanted to limit the surface area of the the exports.

**Comment by adinapoli** [comment]
I see what you mean, but those small combinators are so handy to have when using Lir in 3rd party code, that I think we should take the risk 😉

**Pull request merged**
